FROM ruby:3.0-slim

RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./

COPY greeting.rb .

RUN bundle install 

COPY . . 

EXPOSE 3000 

CMD ["ruby", "greeting.rb"]