version: '3'

services:
  app:
    image: node:18.19.0
    tty: true
    command: sh -c "npm install && npm install node-libcurl && npm install -g jest @jworkman-fs/wdv-cli && npm start"
    ports:
      - 8080:8080
    stdin_open: true
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      